aia:
  persist: true
  patternQualifiedNames:
    "com.github.aia.springboot.samples.controller.TestController.**"
  enable: false
spring:
  mvc:
    view:
      suffix: .html
      prefix: /aia/
server:
  port: 8071
