aia:
  persist: true
  patternQualifiedNames:
    "com.github.aia.springboot.samples.controller.**"
  enable: true
spring:
  mvc:
    view:
      suffix: .html
      prefix: /aia/
server:
  port: 8071
